name: DogeFeatures
main: cn.hotdoge.dogefeatures.DogeFeatures
api-version: 1.15
version: 1
author: Doge
commands:
 restartvote:
  description: Vote to restart server.
  permission: restartvote.use
 banvote:
  description: Vote to ban a player.
  permission: banvote.vote
 banvotecreate:
  description: Create a vote to ban a player.
  permission: banvote.create